# .travis.yml
language: node_js
node_js:
  - 0.10
  - 0.8

before_script:
  - psql -c 'create database bookshelf_test;' -U postgres
  - mysql -e 'create database bookshelf_test;'

notifications:
  email: false